"use strict";
// SE port: CS:GO's panorama scripts call a set of global objects (MyPersonaAPI, PartyListAPI,
// CompetitiveMatchAPI, TournamentsAPI, GameInterfaceAPI, ...) that CS:GO's cstrike15 game DLL
// registers into the script engine.  This port has no cstrike15 client, so every CS:GO script
// aborted on its first reference - mainmenu.js died on line 8 - and the menu never faded in.
// This file installs inert, self-returning stand-ins for every global the CS:GO scripts touch,
// plus tolerant versions of the unhandled-event registration calls, so the scripts run to the end.
// Generated by build/_mkshim.ps1 from the shipped scripts; the name list is machine generated.
(function () {
	var g = Function("return this")();

	// SE port: start timestamp for the injection cost probe.  Every layout gets its own JavaScript
	// context (CUIPanel::BLoadLayout deletes and recreates it), so the three injected files run again
	// on *every page navigation* - the session sim (loaded last) reports the total as a JSINIT line.
	g.SE_PORT_JS_T0 = Date.now();

	// Every stub carries two side tables:
	//   overrides - entries installed by seDefine() below; they win over the placeholder behaviour,
	//               which is how a call can be made to answer with a real 0/false/"{}" instead of
	//               another truthy stub (see the "control flow" note further down).
	//   children  - memoised child stubs, so Api.Foo === Api.Foo (identity stability).
	function makeStub(name) {
		var overrides = Object.create(null);
		var children = Object.create(null);
		var fn = function () { return makeStub(name + "()"); };
		return new Proxy(fn, {
			get: function (target, prop) {
				if (typeof prop === "symbol") {
					// ToPrimitive: JS coerces the stub whenever it lands in a JSON.parse()/string/number
					// sink.  A stub is an object, so it is *always* truthy and it can never look like a
					// "no data" answer; at least make the coercions harmless - an empty document parses,
					// and arithmetic sees 0.
					if (prop === Symbol.toPrimitive) {
						return function (hint) { return hint === "number" ? 0 : "[]"; };
					}
					return undefined;
				}
				if (hasOwn(overrides, prop)) { return overrides[prop]; }
				// hasOwnProperty has to behave like the real one: several CS:GO scripts gate on
				// "Jso.hasOwnProperty('eventdata')", and a stub hands out a *stub* for any method call -
				// which is truthy, so the script walked into branches that expected real data
				// (mainmenu_watch.js:289 was that shape).
				if (prop === "hasOwnProperty") { return function () { return false; }; }
				// Behave like an empty collection: panorama converts .length results straight into numbers, and a
				// stub object there made V8ParamToPanoramaType throw (and the throw took the game down).
				if (prop === "length" || prop === "size" || prop === "count") { return 0; }
				// Explicit .toString()/.valueOf() calls (and anything that does not go through
				// ToPrimitive) also get the harmless empty-document / zero answer.
				if (prop === "toString") { return function () { return "[]"; }; }
				if (prop === "valueOf") { return function () { return 0; }; }
				if (prop === "then") { return undefined; } // do not look like a promise
				if (!hasOwn(children, prop)) { children[prop] = makeStub(name + "." + String(prop)); }
				return children[prop];
			},
			set: function (target, prop, value) {
				if (typeof prop === "string") { overrides[prop] = value; }
				return true;
			},
			apply: function () { return makeStub(name + "()"); },
			construct: function () { return makeStub(name + "()"); },
			has: function () { return true; }
		});
	}

	function hasOwn(obj, key) { return Object.prototype.hasOwnProperty.call(obj, key); }

	var names = [
		"AcknowledgeItems",
		"AdvertisingToggle",
		"Avatar",
		"BlogAPI",
		"BuyMenu",
		"CalcItemCounts",
		"CapabiityHeader",
		"CapabilityCanStatTrackSwap",
		"CapabilityCanSticker",
		"CapabilityDecodable",
		"CapabilityNameable",
		"CapabilityOperationStore",
		"CharacterAnims",
		"CharacterButtons",
		"CharacterLineUp",
		"Chat",
		"Collapse",
		"CommonUtil",
		"CompetitiveMatchAPI",
		"ConstructBaseVoteIssue",
		"ConstructBaseVoteIssueEnabled",
		"Crafting",
		"Data",
		"DateUtil",
		"DeepStatsAPI",
		"DigitPanelFactory",
		"DirectChallengeCheckBox",
		"EmbeddedStreamAPI",
		"EndOfMatch",
		"EOM_Characters",
		"EOM_Podium",
		"EquipNotification",
		"EquipSpray",
		"EventUtil",
		"FlipPanelAnimation",
		"FormatText",
		"FriendAdvertiseTile",
		"FriendsListAPI",
		"Game",
		"GameInterfaceAPI",
		"GameModeFlags",
		"GameStateAPI",
		"GameTypesAPI",
		"HudEdgePositions",
		"HudMissionPanel",
		"HudWinPanel",
		"IconUtil",
		"InpsectPurchaseBar",
		"InspectActionBar",
		"InspectAsyncActionBar",
		"InspectHeader",
		"InspectModelImage",
		"InventoryAPI",
		"InventoryInspect",
		"InventoryPanel",
		"InventorySearch",
		"ItemContextEntires",
		"ItemDef",
		"ItemInfo",
		"ItemModelPanelCharWeaponInspect",
		"ItemTile",
		"LastMatch",
		"LeaderboardsAPI",
		"LicenseUtil",
		"LimitedTest",
		"LoadingScreen",
		"Loadout",
		"LoadoutAPI",
		"LobbyAPI",
		"MainMenu",
		"MainMenuStore",
		"MainMenuTournamentPassStatus",
		"MainmenuWatchNotice",
		"MapDraft",
		"MapSpiderGraph",
		"MatchDraftAPI",
		"MatchIds",
		"MatchIdsFiltered",
		"MatchInfoAPI",
		"MatchListAPI",
		"MatchLister",
		"MatchmakingReconnect",
		"MatchStats",
		"MatchStatsAPI",
		"MedalsAPI",
		"MissionsAPI",
		"MOCK_TABLE",
		"MockAdapter",
		"MuteSpinner",
		"MyPersonaAPI",
		"NewsAPI",
		"NewsPanel",
		"NextPanel",
		"OnActivate",
		"OnActivateRadioButton",
		"OnActivateShowHideConfirm",
		"OnItemPressed",
		"OnMouseOut",
		"OnMouseOutButton",
		"OnMouseOver",
		"OnMouseOverButton",
		"OnMouseOverMapTile",
		"OnSelected",
		"OnSimpleContextMenu",
		"OpBalanceReminder",
		"OpenContextMenu",
		"OperationInspect",
		"OperationMain",
		"OperationMainMenu",
		"OperationMission",
		"OperationMissionCard",
		"OperationMissions",
		"OperationStore",
		"OperationStoreInspect",
		"OperationTiers",
		"OperationUtil",
		"OptionsMenuAPI",
		"OverwatchAPI",
		"PanelPos",
		"PanoramaUI",
		"ParamsList",
		"PartyBrowserAPI",
		"PartyListAPI",
		"PartyMenu",
		"PerfItemJsContext",
		"PerfItemJsContextSingle",
		"PickemCommon",
		"PickEmInfoBar",
		"PlaqueBg",
		"PlayerStats_Web_Weapons",
		"PlayMenu",
		"PopupAcceptMatch",
		"PopupAddFriend",
		"PopupCommendPlayer",
		"PopupConfirmPickemPicks",
		"PopupGoTeamMatchmaking",
		"PopupLeaderboards",
		"PopupLimitedTest",
		"PopupNews",
		"PopupPrimeStatus",
		"PopupRedeemSouvenir",
		"PopupTournamentControlRoom",
		"PopupTournamentPickBan",
		"PopupVanitySettings",
		"PredictionsAPI",
		"ProEventJSO",
		"PromotedSettingsUtil",
		"PurchaseComplete",
		"RadarCTLogo",
		"RadarTLogo",
		"RewardItemGroups",
		"RSSFeedPanel",
		"Scheduler",
		"Scoreboard",
		"SessionUtil",
		"SetItemsToOffer",
		"SettingsMenu",
		"SettingsMenuGameSettings",
		"SettingsMenuPromoted",
		"SettingsMenuSearch",
		"SettingsMenuShared",
		"Slot",
		"StarsShoppingCart",
		"SteamOverlayAPI",
		"StoreAPI",
		"StreamPanel",
		"StreamsAPI",
		"SurvivalWinner",
		"SurvivalZoneTimer",
		"TeamColor",
		"TeammatesAPI",
		"TeamSelectMenu",
		"TintSprayIcon",
		"TooltipLobby",
		"TournamentJournal",
		"TournamentsAPI",
		"TournamentStore",
		"UIPanorama",
		"UiToolkitAPI",
		"UpdatePrediction",
		"Versus",
		"VersusCharactersMine",
		"VoteIssues",
		"VoteTeamSwitch",
		"WorkshopAPI",
		"XmlName"
	];

	for (var i = 0; i < names.length; i++) {
		var n = names[i];
		try { if (typeof g[n] === "undefined") { g[n] = makeStub(n); } } catch (e) { }
	}

	// panorama throws when a script registers for an event that no C++ code has declared; these
	// wrappers turn that into a no-op so a missing event cannot abort a whole script.
	// NOTE: do not try to declare the missing event from here - calling $.DefineEvent for a name that
	// panorama already knows *replaces* the C++ factory (and turns panel events into plain events),
	// which destabilises handlers.  Unknown names are declared on demand in C++ instead.
	function tolerant(name) {
		if (typeof $ === "undefined") { return; }
		var orig = $[name];
		if (typeof orig !== "function") { return; }
		$[name] = function () { try { return orig.apply($, arguments); } catch (e) { return 0; } };
	}
	tolerant("RegisterForUnhandledEvent");
	tolerant("UnregisterForUnhandledEvent");
	tolerant("RegisterEventHandler");
	tolerant("UnregisterEventHandler");

	// CS:GO scripts call $.LocalizeSafe(), which this engine build does not expose at all: "TypeError:
	// $.LocalizeSafe is not a function" aborted SetupPopup() of the game-mode flags popup
	// (popups/popup_play_gamemodeflags.js:8, the dialog behind a mode click) and the WATCH page's
	// event schedule (mainmenu_watch_eventsched.js:410) plus commonutil.js' country/language names.
	// Semantics: like $.Localize but it never fails - a missing key hands the raw token back.
	if (typeof $ !== "undefined" && typeof $.LocalizeSafe !== "function") {
		$.LocalizeSafe = function (token) {
			try {
				var s = $.Localize(token);
				return (s === undefined || s === null || s === "") ? token : s;
			} catch (e) { return token; }
		};
	}

	// Install an override on a dotted API path ("MatchStatsAPI.GetUiExperienceType"), creating the
	// intermediate stubs on the way.  The value lands in the stub's override table (see makeStub).
	function seDefine(path, impl) {
		try {
			var parts = path.split(".");
			if (typeof g[parts[0]] === "undefined") { g[parts[0]] = makeStub(parts[0]); }
			var cur = g[parts[0]];
			for (var i = 1; i < parts.length - 1; i++) { cur = cur[parts[i]]; }
			cur[parts[parts.length - 1]] = impl;
		} catch (e) { }
	}

	// ------------------------------------------------------------------------------------------
	// Typed answers for the calls whose *result* decides control flow.
	//
	// A stub object is always truthy, so "if ( Api.GetSomething() ) return;" silently takes the
	// early-out branch and the button that ran that snippet appears dead, while
	// "if ( Api.GetX() !== false ) { ...popup...; return false; }" takes the error branch.  These
	// are the gates the CS:GO main menu walks through; each answer below is the truth for this port
	// (no GC connection, no license, no item schema), not a placeholder.
	// ------------------------------------------------------------------------------------------

	// mainmenu.js::_OpenPlayMenu -> "if ( MatchStatsAPI.GetUiExperienceType() ) return;" - 0 means
	// the normal main menu experience; anything truthy makes the Play button do nothing.
	seDefine("MatchStatsAPI.GetUiExperienceType", function () { return 0; });

	// mainmenu.js::_BCheckTabCanBeOpenedRightNow -> "restrictions = LicenseUtil.GetCurrentLicenseRestrictions();
	// if ( restrictions !== false ) { LicenseUtil.ShowLicenseRestrictions(...); return false; }".
	// false = "no restrictions", which is what this port has; a stub object here blocks the tab.
	// NOTE: LicenseUtil is a *script* global (common/licenseutil.js) and replaces this stub as soon as
	// that file runs, so the answer below only covers the window before it loads - the real switch on
	// MyPersonaAPI.GetLicenseType() is what normally decides, hence the "purchased" answer two lines on.
	seDefine("LicenseUtil.GetCurrentLicenseRestrictions", function () { return false; });

	// licenseutil.js::_GetCurrentLicenseRestrictions() switches on GetLicenseType():
	// "purchased" is the only case that answers false ("no restrictions"); every other value - and the
	// stub - falls through to a license popup, which would make the Store/Inventory/Watch tabs refuse
	// to open.  A port that owns no license data is the "full" case as far as the UI is concerned.
	seDefine("MyPersonaAPI.GetLicenseType", function () { return "purchased"; });

	// APIs documented to return a JSON document.  The generic stub already stringifies to "[]" (which
	// parses), but an empty document of the right shape keeps the callers on their empty-data path
	// instead of on "unexpected token" exceptions.
	seDefine("InventoryAPI.BuildItemSchemaDefJSON", function () { return "{}"; });
	seDefine("InventoryAPI.GetEconItemDefinition", function () { return "{}"; });
	seDefine("InventoryAPI.GetInventoryStructureJSON", function () { return "{}"; });
	seDefine("LoadoutAPI.GetLoadoutSlotNames", function () { return "[]"; });

	// APIs whose result is passed straight into a C++ binding that insists on a bool: the placeholder
	// object would be coerced by V8 to "" and the binding throws
	// ("V8ParamToPanoramaType expected bool type to convert, but got something else ([])"), which
	// aborts the whole script.  Observed in mainmenu_inventory.js:727
	// (elInvLoadoutBtn.enabled = LoadoutAPI.IsLoadoutAllowed()).
	// The answer has to be a real bool.  It is "true" now that the loadout panel is ported
	// (CCSGO_Loadout in panoramauiclient/csgo_loadout.*): the content enables the "Loadout" button and
	// shows #tooltip_loadout_disabled ("Loadout is not available at this time") while this is false.
	seDefine("LoadoutAPI.IsLoadoutAllowed", function () { return true; });

	// Same failure one level deeper: mainmenu.js::_UpdateUnlockCompAlert() builds
	//
	//     var bHide = GameInterfaceAPI.GetSettingString( ... ) === '1' ||
	//                 MyPersonaAPI.HasPrestige() ||
	//                 MyPersonaAPI.GetCurrentLevel() !== 2;
	//     alert.SetHasClass( 'hidden', bHide );
	//
	// With HasPrestige() a truthy placeholder the "||" returns that object (not a bool) and
	// SetHasClass() throws - so both of these have to answer their real type: false and 2 make the
	// expression a plain "false" and the alert stays visible (which is the pre-unlock state CS:GO
	// shows on a fresh account).
	seDefine("MyPersonaAPI.HasPrestige", function () { return false; });
	seDefine("MyPersonaAPI.GetCurrentLevel", function () { return 2; });

	// The player card / friend tiles assign the value of MyPersonaAPI.GetXuid() straight into the
	// avatar panel:
	//
	//     avatar.js::_SetImage -> elImage.steamid = xuid      (CSGOAvatarImage's "steamid" accessor)
	//
	// A placeholder function object would reach that C++ string setter, where "[]" (the stub's
	// toString) is not a usable id, and every card would fall back to the same picture.  Answering a
	// real-looking 64-bit id keeps the JS contract ("xuid is a string of digits") intact and makes the
	// avatar path deterministic:
	//
	//     materials/panorama/images/avatars/76561198000000001.png   <- this account's avatar
	//     materials/panorama/images/avatars/local.png               <- everyone else
	//
	// (The port's CSGOAvatarImage never talks to Steam; it looks for a file, see
	// panorama/seport/gameclient/cstrike15/panorama/csgo_avatarimage.cpp.)
	seDefine("MyPersonaAPI.GetXuid", function () { return "76561198000000001"; });
	seDefine("MyPersonaAPI.GetAccountID", function () { return 12345678; });

	// ------------------------------------------------------------------------------------------
	// The player card (layout/playercard.xml, loaded by friendslist.js into the top of the sidebar
	// and by context_menu_playercard.js) reads a whole profile through FriendsListAPI/InventoryAPI.
	// Every call below answers a stub object unless it is defined here, and a stub object is caught
	// three different ways by playercard.js:
	//
	//   * "elNameLabel.text = FriendsListAPI.GetFriendName( xuid )" - the name label ends up with
	//     "[object ...]" (or the assignment throws), i.e. the card has an avatar and no name;
	//   * "if ( !flairItems )" - a truthy count walks into a loop that builds one <Image> per entry,
	//     each with src "file://{images_econ}[]_small.png": a picture that cannot load;
	//   * "!teamName || !tournamentName" - both truthy, so the card shows the team/tournament row
	//     with an image path built from "undefined" and a label set to an object.
	//
	// So the answers here are the local profile this port can actually have: a name, level 2 (the
	// same level MyPersonaAPI.GetCurrentLevel() reports), and "0 / empty" for everything that is
	// econ-backed.  The zeroes are not placeholders - they are what makes playercard.js take its
	// "hide this row" branch instead of building a broken image.
	//
	// NOTE: this content version hides the level/XP/rank rows itself (playercard.js: _SetRank(),
	// _SetAllSkillGroups() and _SetPrimeUpsell() all begin with "addClass('hidden'); return;"), so
	// those are not missing data down here - CS:GO does not show them either.  What is left to fill
	// is the name.
	var SE_LOCAL_PLAYER_NAME = "本地玩家";
	seDefine("FriendsListAPI.GetFriendName", function (xuid) { return SE_LOCAL_PLAYER_NAME; });
	seDefine("FriendsListAPI.GetFriendLevel", function (xuid) { return 2; });
	seDefine("FriendsListAPI.GetFriendXp", function (xuid) { return 0; });
	// 0 display items -> playercard.js hides the flair carousel instead of building images from the
	// econ tree, which this port has no images for.
	seDefine("FriendsListAPI.GetFriendDisplayItemDefCount", function (xuid) { return 0; });
	seDefine("FriendsListAPI.GetFriendDisplayItemDefFeatured", function (xuid) { return 0; });
	seDefine("FriendsListAPI.GetFriendDisplayItemDefByIndex", function (xuid, i) { return 0; });
	// no rank data -> -1 is "still loading" to playercard.js, 0 wins keeps it out of the win texts.
	seDefine("FriendsListAPI.GetFriendCompetitiveRank", function (xuid, type) { return -1; });
	seDefine("FriendsListAPI.GetFriendCompetitiveWins", function (xuid, type) { return 0; });
	seDefine("FriendsListAPI.GetFriendMedalRankByType", function (xuid, type) { return 0; });
	// 1 commendation of each kind -> the three thumbs stay visible with a count in the label (0 would
	// hide them; the generic stub object made them visible but put an object where the count goes).
	seDefine("FriendsListAPI.GetFriendCommendations", function (xuid, key) { return 1; });
	// prime badge: shown (the generic stub made it show too, so this keeps the card the user is used to).
	seDefine("FriendsListAPI.GetFriendPrimeEligible", function (xuid) { return true; });
	seDefine("FriendsListAPI.GetFriendRelationship", function (xuid) { return "friend"; });
	seDefine("FriendsListAPI.GetFriendStatusBucket", function (xuid) { return ""; });
	seDefine("FriendsListAPI.GetFriendStatus", function (xuid) { return ""; });

	// "0" is the item id this port uses for "no item"; GetItemInventoryImage("") makes the callers
	// build "file://{images_econ}_small.png" no more - see _SetPlayerBackground/_MakeFlairCarouselPages.
	seDefine("InventoryAPI.GetFauxItemIDFromDefAndPaintIndex", function (def, paint) { return "0"; });
	seDefine("InventoryAPI.GetItemInventoryImage", function (itemid) { return ""; });
	seDefine("InventoryAPI.GetItemName", function (itemid) { return ""; });
	seDefine("InventoryAPI.GetItemRarityColor", function (itemid) { return ""; });
	seDefine("InventoryAPI.GetFlairItemId", function (xuid) { return "0"; });
	seDefine("InventoryAPI.GetMaxLevel", function () { return 40; });

	// -1 = "no rank for this type", which is also what keeps MyPersonaAPI.GetPipRankWins( "Competitive" )
	// from opening the skill-group block in _FillOutFriendCard().
	seDefine("MyPersonaAPI.GetPipRankWins", function (type) { return -1; });
	seDefine("MyPersonaAPI.GetXpPerLevel", function () { return 5000; });
	seDefine("MyPersonaAPI.GetLauncherType", function () { return "steam"; });
	// empty team/tournament -> the card hides its "official team" row instead of showing "undefined".
	seDefine("MyPersonaAPI.GetMyOfficialTeamName", function () { return ""; });
	seDefine("MyPersonaAPI.GetMyOfficialTeamTag", function () { return ""; });
	seDefine("MyPersonaAPI.GetMyOfficialTournamentName", function () { return ""; });

	// avatar.js::_SetTeamColor -> PartyListAPI.GetPartyMemberSetting( xuid, 'game/teamcolor' ):
	// a number (not "") keeps the team colour triangle on the avatar - TeamColor.GetTeamColor() maps
	// 1..4 to an RGB triple.  A stub object here produced a wash colour built from "undefined".
	seDefine("PartyListAPI.GetPartyMemberSetting", function (xuid, key) { return 1; });

	// ------------------------------------------------------------------------------------------
	// No lobby, no party - which in this build is the truth (there is no GC connection, and the
	// friends/party data is local).
	//
	// This matters far more than it looks: party.js::_IsSessionActive() asks LobbyAPI.IsSessionActive()
	// on startup, and with a *truthy* placeholder it believes the player is in a party.  The friends
	// sidebar then switches from the local player card to the party member list:
	//
	//     party.js::_UpdateMembersList() -> $('#PartyList').RemoveClass('hidden')
	//                                   -> friendsList.HideLocalPlayer( true )   // collapses your card
	//
	// i.e. the player card (the panel the top-right avatar lives in) is hidden, its avatar is never
	// laid out - the card area shows the party UI instead, with counts built from more placeholders
	// ("[]/5").  Answering "no session" here makes the script take its own early-out, which is also the
	// path that *shows* the card again: HideLocalPlayer( false ).
	//
	// (See docs/csgo_panorama_port_pitfalls.md: a truthy stub is not a neutral value - it picks the
	// branch that says "the game has data".)
	seDefine("LobbyAPI.IsSessionActive", function () { return false; });
	seDefine("LobbyAPI.BIsHost", function () { return false; });
	seDefine("LobbyAPI.GetHostSteamID", function () { return ""; });
	// GetCount() is what fills the "N/5" party label; with no session the party block stays hidden, but
	// answer a number anyway so any other caller gets a number and not an object.
	seDefine("PartyListAPI.GetCount", function () { return 1; });
	seDefine("PartyListAPI.GetPartySessionUiThreshold", function () { return 5; });
	seDefine("PartyListAPI.GetXuidByIndex", function (i) { return i === 0 ? "76561198000000001" : "0"; });
	// avatar.js::_UpdateTalkingState polls this while the avatar is shown.
	seDefine("PartyListAPI.GetFriendIsTalking", function (xuid) { return false; });
	seDefine("SessionUtil.GetMaxLobbySlotsForGameMode", function (mode) { return 5; });
	seDefine("SessionUtil.GetNumWinsNeededForRank", function (type) { return 10; });
	// no medal data at all -> the medals block loops zero times.
	seDefine("MedalsAPI.GetAchievementMedalTypesCount", function () { return 0; });
	seDefine("MyPersonaAPI.GetAccountID", function () { return 12345678; });

	// The persona/competitive answers that decide whether CS:GO throws a *modal window at the player*
	// whose buttons include "Quit".  Every one of them sits behind a truthiness test in mainmenu.js,
	// so the generic stub object turns "this port has no data" into "there is a problem", and the
	// windows that come out of it end the game when they are clicked:
	//
	//   _GcLogonNotificationReceived (mainmenu.js:189) - a non-empty GetClientLogonFatalError() falls
	//       through to ShowGenericPopupOneOptionBgStyle( "#SFUI_LoginPerfectWorld_Title_Error", ...,
	//       "#GameUI_Quit", function() { GameInterfaceAPI.ConsoleCommand( "quit" ); }, "dim" ): a
	//       window titled like an error whose *only* button quits the game.
	//   _GameMustExitNowForAntiAddiction (mainmenu.js:245) - the same shape with
	//       "#UI_AntiAddiction_ExitGameNowMessage" + "#GameUI_Quit" when
	//       GetTimePlayedTrackingState() > 0.
	//   _GetPopupNotification (mainmenu.js:1396) - shows "#SFUI_MainMenu_ConfirmBan" when
	//       GetCooldownSecondsRemaining() < 0, or when GetMyNotifications() is a non-empty string
	//       (it then calls .split( ',' ) on the result, so returning a string is required).
	//
	// This port owns no GC logon, no anti-addiction schedule and no competitive cooldown, so the empty
	// answers are the truth here.  "" rather than undefined: the callers treat the result as a string.
	seDefine("MyPersonaAPI.GetClientLogonFatalError", function () { return ""; });
	seDefine("MyPersonaAPI.GetTimePlayedTrackingState", function () { return 0; });
	seDefine("MyPersonaAPI.GetMyNotifications", function () { return ""; });
	seDefine("CompetitiveMatchAPI.GetCooldownSecondsRemaining", function () { return 0; });
	seDefine("CompetitiveMatchAPI.GetCooldownReason", function () { return ""; });
	seDefine("CompetitiveMatchAPI.GetCooldownType", function () { return ""; });

	// NOTE: deliberately *not* answered here (they stay truthy placeholders, which is the branch the
	// CS:GO menu wants when it is not connected to Steam):
	//   MyPersonaAPI.IsInventoryValid() / IsConnectedToGC()  - "false" makes
	//       _BCheckTabCanBeOpenedRightNow() refuse the Inventory/Stats tabs (it wants to pop up a
	//       Steam-connection error), so the buttons would look dead.
	//   InventoryAPI.GetCacheTypeElementFieldByIndex()       - "undefined" makes
	//       _CanOpenStatsPanel() take its "open the subscription upsell popup instead" path.

	// SE port: the CS:GO main menu background movie is named by a game setting
	// (mainmenu.js::_SetBackgroundMovie -> GameInterfaceAPI.GetSettingString('ui_mainmenu_bkgnd_movie')).
	// Only the cstrike15 client can supply it, so answer with a file that this port ships.  The name
	// is turned into "file://{resources}/videos/<name>.webm" by mainmenu.js.
	//
	// Every other setting answers "" (an unset string), NOT undefined: callers treat the result as a
	// string ("...GetSettingString( 'cl_promoted_settings_acknowledged' ).split( ':' )" in
	// common/promoted_settings.js throws on undefined and takes the whole main menu bootstrap with it).
	// SE port: GameInterfaceAPI is a *real* C++ object now - CS:GO's uicomponent_gameinterface is
	// ported (panorama/seport/gameclient/cstrike15/uicomponents/uicomponent_gameinterface.cpp) and
	// its GetSettingString/SetSettingString read and write the archived ConVars through g_pCVar, which
	// is what makes ui_mainmenu_bkgnd_movie (and with it the background-movie choice) a real setting.
	//
	// The name list above only installs a placeholder when the global is *undefined*, so the real
	// object is left alone.  seDefine() would overwrite its method, so only use it as the fallback for
	// a build without the component - and keep the "unknown setting answers '' (not undefined)"
	// contract either way: several CS:GO scripts call .split() on the result
	// (common/promoted_settings.js) and undefined would take the whole main menu bootstrap down.
	if (typeof g.GameInterfaceAPI === "undefined" ||
		typeof g.GameInterfaceAPI.GetSettingString !== "function") {
		seDefine("GameInterfaceAPI.GetSettingString", function (key) {
			if (key === "ui_mainmenu_bkgnd_movie") { return "anubis720"; }
			return "";
		});
	}

	// ------------------------------------------------------------------------------------------
	// Typed answers for the calls whose *result type* the engine checks (found 2026-09-17 with the
	// JSEXC probe: panorama/uiengine.cpp::OutputJSExceptionToConsole now appends every JS exception to
	// D:\cstrike\se_ui_probe.txt, which is how these were caught - a manual run leaves no other
	// trace).
	//
	// This is a different failure from the truthiness problem above: when the place expects a bool
	// (a panel's `.enabled`, a `var x = Api.IsY()`), the engine converts the JS value with
	// V8ParamToPanoramaType and throws "expected bool type to convert, but got something else ([])"
	// when it finds a stub object - and the throw skips the *rest of the script*.  That is how
	// mainmenu_play.js::_ShowActiveMapSelectionTab() died right after switching the map container
	// (line 1323), so the map list never followed a game mode click, and why several other scripts
	// (crafting, report popup, ...) aborted mid-initialisation.
	// ------------------------------------------------------------------------------------------
	seDefine("SteamOverlayAPI.IsEnabled", function () { return false; });
	seDefine("InventoryAPI.IsCraftReady", function () { return false; });
	seDefine("GameStateAPI.IsReportCategoryEnabledForSelectedPlayer", function (xuid, category) { return false; });

	// InventoryAPI sort methods: mainmenu_inventory.js / mainmenu_inventory_search.js /
	// crafting.js build a sort DropDown from GetSortMethodsCount() + GetSortMethodByIndex(i) and
	// then *select* one of the returned ids.  With the stub the build loop never ran (i < <stub>
	// evaluates to 0) and SetSelected( <stub> ) left the DropDown without any selection, so the next
	// statement (GetSelected().id) threw "Cannot read property 'id' of null" and took the whole
	// inventory / crafting item list with it.  The ids are the localization tokens of the menu
	// entries (csgo_english.txt: inv_sort_*), quality first like the CS:GO menu.
	var SE_SORT_METHODS = [ "inv_sort_rarity", "inv_sort_age", "inv_sort_alpha", "inv_sort_slot",
		"inv_sort_collection", "inv_sort_equipped", "inv_sort_wear", "inv_sort_paint" ];
	seDefine("InventoryAPI.GetSortMethodsCount", function () { return SE_SORT_METHODS.length; });
	seDefine("InventoryAPI.GetSortMethodByIndex", function (i) {
		var idx = Number(i);
		return (idx >= 0 && idx < SE_SORT_METHODS.length) ? SE_SORT_METHODS[idx] : SE_SORT_METHODS[0];
	});

	// Watch -> Tournaments builds its team lists from TournamentsAPI.GetProEventDataJSO(i, 8).
	// With the stub, "ProEventJSO.hasOwnProperty('eventdata')" answered truthy (a stub call returns a
	// stub), so the page believed the event had data and walked into the stub's empty players table
	// (mainmenu_watch.js:289 "Cannot read property '1' of undefined").  {} = "no event data", which
	// keeps the tournament tiles in their "champions TBD" state.
	seDefine("TournamentsAPI.GetProEventDataJSO", function () { return {}; });
})();
// SE port (temporary probe 2026-09-18): hover-delivery check for the tooltip-attribute elements
// (the experiment suggested for the missing tooltips).  Every layout context looks for a few known
// tooltip elements and binds onmouseover/onmouseout probes on them; results are written through the
// GameInterfaceAPI se_probe channel, i.e. they show up as SIMPROBE lines in se_ui_probe.txt.
// Deliberately does NOT touch the navbar buttons (their inline onmouseover already proved the JS
// hover path works, and SetPanelEvent might replace the inline handler).
(function () {
    try {
        if (typeof GameInterfaceAPI === 'undefined' || typeof $ === 'undefined') { return; }
        var seHoverTargets = ['id-tt_gamemodeflags', 'MainMenuMovieSceneSelector', 'LoadoutShuffleControls'];
        var seHoverBound = {};
        var seHoverRounds = 0;
        var seHoverTick = function () {
            try {
                var root = $.GetContextPanel();
                if (root && root.id !== 'se_probe') {
                    for (var i = 0; i < seHoverTargets.length; i++) {
                        var id = seHoverTargets[i];
                        if (seHoverBound[id]) { continue; }
                        var el = null;
                        try { el = root.FindChildTraverse ? root.FindChildTraverse(id) : null; } catch (e1) { }
                        if (!el) { try { el = root.FindChildInLayoutFile ? root.FindChildInLayoutFile(id) : null; } catch (e2) { } }
                        if (el) {
                            seHoverBound[id] = true;
                            (function (boundId, boundEl) {
                                boundEl.SetPanelEvent('onmouseover', function () {
                                    GameInterfaceAPI.SetSettingString('se_probe_hover_' + boundId, 'OVER');
                                });
                                boundEl.SetPanelEvent('onmouseout', function () {
                                    GameInterfaceAPI.SetSettingString('se_probe_hover_' + boundId, 'OUT');
                                });
                            })(id, el);
                            GameInterfaceAPI.SetSettingString('se_probe_hover_bound', id + ' ctx=' + (root.id || '?'));
                        }
                    }
                }
            } catch (e) { }
            seHoverRounds++;
            if (seHoverRounds < 150) { $.Schedule(1.0, seHoverTick); }
        };
        $.Schedule(2.0, seHoverTick);
    } catch (e) { }
})();