//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Purpose: SE port - see se_uicomponents.h next to this file.
//
//=============================================================================//

#include "stdafx_client.h"

// Resolved through the ../panorama/seport/gameclient/cstrike15/uicomponents include dir, which is
// where the ported copy lives (CS:GO spelling, bare name).
#include "uicomponent_uitoolkit.h"

#include "se_uicomponents.h"

// memdbgon must be the last include file in a .cpp file!!!
#include <tier0/memdbgon.h>

void SE_PortInstallUiComponentBindings()
{
	static bool s_bInstalled = false;
	if ( s_bInstalled )
		return;

	if ( !panorama::UIEngine() )
	{
		Warning( "SE port: cannot install the UiToolkitAPI bindings yet - no panorama UIEngine\n" );
		return;
	}

	s_bInstalled = true;

	// CUiComponent_UiToolkit::InstallPanoramaBindings() is generated by
	// UI_COMPONENT_API_DEF_COMMON_DOC( CUiComponent_UiToolkit, UiToolkit, "..." ) ->
	// PANORAMA_COMPONENT_API_INSTALL( ..., "UiToolkitAPI", ... ), which opens the JS scope and exposes
	// the global object described by uicomponent_uitoolkit.functions.inc.
	//
	// The override is protected (UI_COMPONENT_DECLARE_GLOBAL_INSTANCE_ONLY) while
	// IUiComponentGlobalInstanceBase::InstallPanoramaBindings() is public, so call it through the base
	// pointer - exactly what CS:GO's gameui_interface.cpp does with its m_arrUiComponents list.
	IUiComponentGlobalInstanceBase *pUiToolkit = CUiComponent_UiToolkit::GetInstance();
	pUiToolkit->InstallPanoramaBindings();

	Msg( "SE port: installed the UiToolkitAPI JS bindings (CUiComponent_UiToolkit)\n" );

	// SE port: the other two things CS:GO's CGameUI::CreateGameSpecificUI() does before any layout runs -
	// load the game's localization and register the panorama keybindings.
	//
	// Without the localization every "#token" in the CS:GO layouts resolves to nothing (each one logs
	// "**** Unable to localize ..."), which is a large part of why the menu looks empty even when it
	// loads.  The token files ship with this content:
	//     <mod>/resource/csgo_english.txt     -> BLoadLocalizationFile( "csgo" )
	//     <mod>/resource/cstrike_english.txt  -> BLoadLocalizationFile( "cstrike" )
	// (the prefix is resolved against the mod's resource dir and the current language).
	if ( panorama::UILocalize() )
	{
		// These are CS:GO's own calls (CGameUI::CreateGameSpecificUI).  They resolve the prefix against
		// the {localization} named path of the mod's panorama/panorama.cfg and the current UI language,
		// i.e. "<dir>/<prefix>_<language>.txt".  A prefix that walks out of {localization} does NOT
		// work: CLocalization::ConstructLocalizationFilePath() runs the composed path through
		// V_FixupPathName(), which collapses the ".." segments instead of resolving them.
		//
		// This content's cfg (Valve's own) points {localization} at <mod>/panorama/localization, so the
		// mod's resource/csgo_english.txt + cstrike_english.txt have to be present there as well for
		// the tokens to resolve.  See build/_stage_loc.ps1.
		const char *pchLocDir = panorama::UIEngine() ? panorama::UIEngine()->GetLocalPathForNamedPath( "{localization}" ) : "<no engine>";

		const bool bCsgo = panorama::UILocalize()->BLoadLocalizationFile( "csgo" );
		const bool bCstrike = panorama::UILocalize()->BLoadLocalizationFile( "cstrike" );

		// SE port: the port's *own* tokens (the demo news / store text the injected scripts put on
		// screen, and anything else the port needs) live in files the port ships rather than in the
		// game's content: <mod>/panorama/localization/se_port_<language>.txt, with se_port_english.txt
		// as the always-loaded fallback.  They come from mods/panorama_test/panorama/localization/ and
		// are deployed by build/_deploy_se_js.ps1.
		// Loading a prefix with no file is harmless - CLocalization just skips it and reports false,
		// so a build without those files keeps working.
		const bool bSEPort = panorama::UILocalize()->BLoadLocalizationFile( "se_port" );

		Msg( "SE port: localization loaded (csgo=%d cstrike=%d se_port=%d, {localization}='%s')\n",
			(int)bCsgo, (int)bCstrike, (int)bSEPort, pchLocDir ? pchLocDir : "<null>" );
	}
	else
	{
		Warning( "SE port: no CLocalize, the layout tokens will not resolve\n" );
	}

	// CS:GO's CGameUI::CreateGameSpecificUI() registers this file; the shipped content has it.
	if ( panorama::UIInputEngine() )
	{
		panorama::UIInputEngine()->RegisterKeyBindingsFile( "file://{resources}/csgo_keybinds.cfg" );
		Msg( "SE port: registered file://{resources}/csgo_keybinds.cfg\n" );
	}
}
